package:
  name: numpy-allocation-tracking
  version: 0.1

source:
  git_url: ../
  git_tag: HEAD

extra:
  additional-sources:
    numpy:
      git_url: https://github.com/numpy/numpy
      
      # We choose a particular version of the numpy source just for the allocation_tracking extension module,
      # but this recipe can still be built against other versions of numpy.
      # That is, use any value you want for CONDA_NPY when building this recipe.
      git_rev: v1.9.3
      
      patches:
        # This patch changes an import statement for consistency with this package.
        - patches/track_allocations.py.patch

build:
  number: 0
  string: py{{CONDA_PY}}np{{CONDA_NPY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - numpy {{NPY_VER}}*
    - cython
  run:
    - numpy {{NPY_VER}}*

test:
  imports:
    - numpy_allocation_tracking.alloc_hook
    - numpy_allocation_tracking.track_allocations
    - numpy_allocation_tracking.decorators

about:
  home: http://www.numpy.org
  license: BSD
  summary: >
    Allocation tracking utility from the numpy
    source repo (which isn't installed by default),
    plus an extra module with some decorators.
